metal_bands = [
    "Metallica",
    "Slayer",
    "Megadeth",
    "Pantera",
    "Anthrax",
    "Motorhead",
    "Sepultura",
    "Testament",
    "Death",
    "Opeth",
    "Behemoth",
    "Dio",
    "Mastodon",
    "Kreator",
    "Exodus",
    "Carcass",
    "Slipknot",
    "Venom",
    "Helloween",
    "Candlemass",
    "Saxon",
    "Entombed",
    "Gojira",
    "Meshuggah",
    "Sabaton",
    "Behemoth",
    "Stratovarius",
    "Sodom",
    "Mayhem",
    "Ensiferum",
    "Emperor",
    "Suffocation",
    "Obituary",
    "Overkill",
    "Deicide",
    "Darkthrone",
    "Hatebreed",
    "Kamelot",
    "Bathory",
    "Enslaved",
    "Sabaton",
    "Satyricon",
    "Nile",
    "Annihilator",
    "Therion",
    "Destruction",
    "Amorphis",
    "Devildriver",
    "Moonspell",
    "Ghost",
    "Carcass",
    "Nevermore",
    "Angra",
    "Kalmah",
    "Soilwork",
    "Borknagar",
    "Epica",
    "Meshiaak",
    "Abbath",
    "Equilibrium",
    "Myrath",
    "Powerwolf",
    "Vader",
    "Samael",
    "Havok",
    "Warbringer",
    "Revocation",
    "Wintersun"
    "Manowar"
    "Konstrust"
    "Saurom"
    "Alestorm"
    "Arkona"
    "Eluveitie"
    "Faun"
    "Heilung"
    "Kalevala"
    "Korpiklaani"
    "Manegarm"
    "Nightwish"
    "Turisas"
    "Tyr"
    "Wardruna"
]
